name: CI/CD Frontend

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: fe_MiseEnPlace

      - name: Set CI environment variable to false
        run: echo "CI=false" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: List directory structure
        run: ls -R

      - name: Install dependencies
        run: npm install
        working-directory: ./fe_MiseEnPlace/mise-en-place/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Start application on remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ubuntu
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/fe_MiseEnPlace/ # Navega até o diretório do projeto
            git checkout main # Certifica-se de que está na branch main
            git pull # Atualiza o código
            cd mise-en-place/ # Navega até o diretório do frontend
            npm install # Certifica-se de que as dependências estão instaladas
            sudo npm install pm2 -g # Instala o pm2 globalmente
            pm2 start npm -- start # Inicia o servidor usando pm2
