# Configuração do workflow para deploy do frontend React
name: CI/CD fe

on:
  pull_request:
    branches:
      - main # Executa o workflow ao fazer push na branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Atualizar o código
      uses: actions/checkout@v2
      with:
        path: fe_MiseEnPlace

    - name: Set CI environment variable to false
      run: echo "CI=false" >> $GITHUB_ENV

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22' # Especifica a versão do Node.js

    - name: List directory structure
      run: ls -R

    - name: Instalar dependências
      run: npm install
      working-directory: ./fe_MiseEnPlace/mise-en-place/

    - name: Gerar build do React
      run: npm run build # Gera os arquivos estáticos para deploy
      working-directory: ./fe_MiseEnPlace/mise-en-place/

    - name: Gerar artefato Github com os arquivos do build
      uses: actions/upload-artifact@v4
      with:
        name: build-frontend
        path: ./fe_MiseEnPlace/mise-en-place/build/ # Diretório gerado pelo npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Recuperar artefatos do build
      uses: actions/download-artifact@v4
      with:
        name: build-frontend
        path: ./fe_MiseEnPlace/mise-en-place/build/

    - name: Criar arquivo .pem a partir da variável DEPLOY_KEY e fazer o chmod 400 nele
      id: criar-arquivo-pem
      run: |
        echo "${{ secrets.DEPLOY_KEY }}" >> $HOME/public-key.pem
        chmod 400 $HOME/public-key.pem

    - name: Enviar arquivos do build para a EC2 via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ubuntu
        key: 
        port: 22
        source: "./fe_MiseEnPlace/mise-en-place/build/"
        target: "/home/ubuntu/"

    - name: Transfer JAR to Public EC2
      uses: appleboy/scp-action@v0.1.6
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ubuntu
        key: $HOME/public-key.pem
        source: "target/*.jar"
        target: "temporaria/"


    - name: Ajustar permissões no servidor remoto
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ubuntu
        key: ${{ secrets.DEPLOY_KEY }}
        port: 22
        script: |
          chown -R ubuntu:ubuntu /home/ubuntu/Desktop/Frontend/
          chmod -R 770 /home/ubuntu/Desktop/Frontend/