name: Pipeline CI/CD Front-end

on:
  push:
    branches:
      - main # Executa o workflow ao fazer push na branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Atualizar o código
      uses: actions/checkout@v2
      with:
        path: fe_MiseEnPlace

    - name: Set CI environment variable to false
      run: echo "CI=false" >> $GITHUB_ENV

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Especifica a versão do Node.js

    - name: List directory structure
      run: ls -R

    - name: Instalar dependências
      run: npm install
      working-directory: ./fe_MiseEnPlace/mise-en-place

    - name: Gerar build do React
      run: npm run build # Gera os arquivos estáticos para deploy
      working-directory: ./fe_MiseEnPlace/mise-en-place

    - name: Gerar artefato Github com os arquivos do build
      uses: actions/upload-artifact@v4
      with:
        name: build-frontend
        path: ./fe_MiseEnPlace/mise-en-place/build # Diretório gerado pelo npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Recuperar artefatos do build
      uses: actions/download-artifact@v4
      with:
        name: build-frontend
        path: ./fe_MiseEnPlace/mise-en-place/build

    - name: Criar PEM EC2 Publica
      id: criar-arquivo-pem
      run: |
        echo "${{ secrets.PUBLIC_EC2_KEY }}" >> $HOME/public-key.pem
        chmod 400 $HOME/public-key.pem

    - name: Enviar arquivos do build para a EC2 via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.PUBLIC_EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.PUBLIC_EC2_KEY }}
        port: 22
        source: "./fe_MiseEnPlace/mise-en-place/build/"
        target: "/home/ubuntu/"

    - name: Ajustar permissões no servidor remoto
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ubuntu
        key: ${{ secrets.DEPLOY_KEY }}
        port: 22
        script: |
          chown -R ubuntu:ubuntu /home/ubuntu/
          chmod -R 770 /home/ubuntu/